name: Feature request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What's the problem?
      description: What are you trying to accomplish?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed approach
    validations:
      required: false
